### ISSUE TITLE
Improve Arguments / Options Handling

### ISSUE THREAD

**Issue by christophwille** [christophwille/ilspy-console-netcoreapp#2]
E.g. providing invalid option yields exception:

PS D:\GitWorkspace\ilspy-console-netcoreapp\src\ilspycmd> dotnet run -- -j
Using launch settings from D:\GitWorkspace\ilspy-console-netcoreapp\src\ilspycmd\Properties\launchSettings.json...
Specify --help for a list of available options and commands.

Unhandled Exception: McMaster.Extensions.CommandLineUtils.CommandParsingException: Unrecognized option '-j'
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at ilspycmd.Program.Main(String[] args) in D:\GitWorkspace\ilspy-console-netcoreapp\src\ilspycmd\Program.cs:line 77

**Comment by christophwille** [comment]
See https://github.com/christophwille/ilspy-console-netcoreapp/commit/5665faf4661e3a21a38067e03f2b7ad6ce3d6af5#diff-e14adb97eb42cdb055e40aedc67fac4aR33
